default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "localhost" %>


development:
  <<: *default
  database: hex_world_development


test:
  <<: *default
  database: hex_world_test


production:
  primary: &primary_production
    <<: *default
    database: hex_world_production
    username: hex_world
    password: <%= ENV["HEX_WORLD_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: hex_world_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: hex_world_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: hex_world_production_cable
    migrations_paths: db/cable_migrate
